"""AI prompt anlatımı için BIST kısa adları.

Bu sözlük yalnızca AI'ın kullanıcıya görünen doğal dilinde kullanılır.
Arayüz, tarama, veri ve sembol kimlikleri bu dosyadan etkilenmez.
"""

AI_NARRATIVE_SHORT_NAMES = {
    "A1CAP": "A1 Capital",
    "AAGYO": "Ağaoğlu GYO",
    "ACSEL": "Acıselsan",
    "ADEL": "Adel",
    "ADESE": "Adese",
    "ADGYO": "Adra GYO",
    "AEFES": "Anadolu Efes",
    "AFYON": "Afyon Çimento",
    "AGESA": "Agesa",
    "AGHOL": "Anadolu Grup",
    "AGROT": "Agrotech",
    "AGYO": "Atakule GYO",
    "AHGAZ": "Ahlatcı Gaz",
    "AHSGY": "Ahes GYO",
    "AKBNK": "Akbank",
    "AKCNS": "Akçansa",
    "AKENR": "Akenerji",
    "AKFGY": "Akfen GYO",
    "AKFIS": "Akfen İnşaat",
    "AKFYE": "Akfen",
    "AKGRT": "Ak Sigorta",
    "AKHAN": "Akhan Un",
    "AKMGY": "Akmerkez GYO",
    "AKSA": "Aksa",
    "AKSEN": "Aksa Enerji",
    "AKSGY": "Akiş GYO",
    "AKSUE": "Aksu Enerji",
    "AKYHO": "Akdeniz Yatırım",
    "ALARK": "Alarko",
    "ALBRK": "Albaraka Türk",
    "ALCAR": "Alarko Carrier",
    "ALCTL": "Alcatel Lucent",
    "ALFAS": "Alfa Solar",
    "ALGYO": "Alarko GYO",
    "ALKA": "Alkim Kağıt",
    "ALKIM": "Alkim",
    "ALKLC": "Altınkılıç",
    "ALTNY": "Altınay Savunma",
    "ALVES": "Alves Kablo",
    "ANELE": "Anel Elektrik",
    "ANGEN": "Anatolia Tanı",
    "ANHYT": "Anadolu Hayat",
    "ANSGR": "Anadolu Sigorta",
    "ARASE": "Aras Enerji",
    "ARCLK": "Arçelik",
    "ARDYZ": "Ard Grup",
    "ARENA": "Arena Bilgisayar",
    "ARFYE": "ARF Bio",
    "ARMGD": "Armada Gıda",
    "ARSAN": "Arsan",
    "ARTMS": "Artemis Halı",
    "ARZUM": "Arzum",
    "ASELS": "Aselsan",
    "ASGYO": "ASCE GYO",
    "ASTOR": "Astor Enerji",
    "ASUZU": "Anadolu Isuzu",
    "ATAGY": "Ata GYO",
    "ATAKP": "Atakey",
    "ATATP": "ATP Yazılım",
    "ATATR": "Ata Turizm",
    "ATEKS": "Akın Tekstil",
    "ATLAS": "Atlas Yatırım",
    "ATSYH": "Atlantis Yatırım",
    "AVGYO": "Avrasya GYO",
    "AVHOL": "Avrupa Holding",
    "AVOD": "AVOD Gıda",
    "AVPGY": "Avrupakent GYO",
    "AVTUR": "Avrasya Petrol",
    "AYCES": "Altın Yunus",
    "AYDEM": "Aydem Enerji",
    "AYEN": "Ayen Enerji",
    "AYES": "Ayes Çelik",
    "AYGAZ": "Aygaz",
    "AZTEK": "Aztek",
    "BAGFS": "Bagfaş",
    "BAHKM": "Bahadır Kimya",
    "BAKAB": "Bak Ambalaj",
    "BALAT": "Balatacılar",
    "BALSU": "Balsu",
    "BANVT": "Banvit",
    "BARMA": "Barem",
    "BASCM": "Baştaş",
    "BASGZ": "Başkent Gaz",
    "BAYRK": "Bayrak EBT",
    "BEGYO": "Batı Ege",
    "BERA": "Bera Holding",
    "BESLR": "Besler Gıda",
    "BESTE": "Best Brands",
    "BETAE": "Beta Enerji",
    "BEYAZ": "Beyaz Filo",
    "BFREN": "Bosch Fren",
    "BIENY": "Bien Seramik",
    "BIGCH": "BigChefs",
    "BIGEN": "Birleşim Enerji",
    "BIGTK": "Big Medya",
    "BIMAS": "BİM",
    "BINBN": "BinBin",
    "BINHO": "1000 Yatırımlar",
    "BIOEN": "Biotrend",
    "BIZIM": "Bizim Toptan",
    "BJKAS": "Beşiktaş",
    "BLCYT": "Bilici",
    "BLUME": "Blume Metal",
    "BMSCH": "BMS Çelik",
    "BMSTL": "BMS Birleşik",
    "BNTAS": "Bantaş",
    "BOBET": "Boğaziçi Beton",
    "BORLS": "Borlease",
    "BORSK": "Bor Şeker",
    "BOSSA": "Bossa",
    "BRISA": "Brisa",
    "BRKO": "Birko",
    "BRKSN": "Berkosan",
    "BRKVY": "Birikim Varlık",
    "BRLSM": "Birleşim Mühendislik",
    "BRMEN": "Birlik Mensucat",
    "BRSAN": "Borusan",
    "BRYAT": "Borusan Yatırım",
    "BSOKE": "Batısöke",
    "BTCIM": "Batıçim",
    "BUCIM": "Bursa Çimento",
    "BULGS": "Bulls Girişim",
    "BURCE": "Burçelik",
    "BURVA": "Burçelik Vana",
    "BVSAN": "Bülbüloğlu Vinç",
    "BYDNR": "Baydöner",
    "CANTE": "Çan2 Termik",
    "CATES": "Çates Elektrik",
    "CCOLA": "Coca-Cola",
    "CELHA": "Çelik Halat",
    "CEMAS": "Çemaş",
    "CEMTS": "Çemtaş",
    "CEMZY": "Cem Zeytin",
    "CEOEM": "CEO Event",
    "CGCAM": "Çağdaş Cam",
    "CIMSA": "Çimsa",
    "CLEBI": "Çelebi",
    "CMBTN": "Çimbeton",
    "CMENT": "Çimentaş",
    "CONSE": "Consus Enerji",
    "COSMO": "Cosmos Yatırım",
    "CRDFA": "Creditwest",
    "CRFSA": "CarrefourSA",
    "CUSAN": "Çuhadaroğlu",
    "CVKMD": "CVK Maden",
    "CWENE": "CW Enerji",
    "DAGI": "Dagi",
    "DAPGM": "DAP GYO",
    "DARDL": "Dardanel",
    "DCTTR": "DCT Trading",
    "DENGE": "Denge Yatırım",
    "DERHL": "Derlüks",
    "DERIM": "Derimod",
    "DESA": "Desa",
    "DESPC": "Despec",
    "DEVA": "Deva",
    "DGATE": "Datagate",
    "DGGYO": "Doğuş GYO",
    "DGNMO": "Doğanlar Mobilya",
    "DIRIT": "Diriteks",
    "DITAS": "Ditaş",
    "DMRGD": "DMR Unlu",
    "DMSAS": "Demisaş",
    "DNISI": "Dinamik Isı",
    "DOAS": "Doğuş Otomotiv",
    "DOCO": "DO&CO",
    "DOFER": "Dofer",
    "DOFRB": "DOF Robotik",
    "DOGUB": "Doğusan",
    "DOHOL": "Doğan Holding",
    "DOKTA": "Döktaş",
    "DSTKF": "Destek Finans",
    "DUNYH": "Dünya Holding",
    "DURDO": "Duran Doğan",
    "DURKN": "Durukan",
    "DYOBY": "DYO Boya",
    "DZGYO": "Deniz GYO",
    "EBEBK": "ebebek",
    "ECILC": "Eczacıbaşı İlaç",
    "ECOGR": "Ecogreen",
    "ECZYT": "Eczacıbaşı Yatırım",
    "EDATA": "E-Data",
    "EDIP": "Edip GYO",
    "EFOR": "Efor Yatırım",
    "EGEEN": "Ege Endüstri",
    "EGEGY": "Egeyapı",
    "EGEPO": "Nasmed",
    "EGGUB": "Ege Gübre",
    "EGPRO": "Ege Profil",
    "EGSER": "Ege Seramik",
    "EKDMR": "Ekinciler",
    "EKGYO": "Emlak Konut",
    "EKIM": "Ekim Turizm",
    "EKIZ": "Ekiz Kimya",
    "EKOS": "Ekos Teknoloji",
    "EKSUN": "Eksun",
    "ELITE": "Elite Naturel",
    "EMKEL": "Emek Elektrik",
    "EMNIS": "Eminiş",
    "EMPAE": "Empa Elektronik",
    "ENDAE": "Enda Enerji",
    "ENERY": "Enerya",
    "ENJSA": "Enerjisa",
    "ENKAI": "Enka",
    "ENPRA": "Enpara",
    "ENSRI": "Ensari",
    "ENTRA": "IC Enterra",
    "EPLAS": "Egeplast",
    "ERBOS": "Erbosan",
    "ERCB": "Erciyas Çelik",
    "EREGL": "Erdemir",
    "ERSU": "Ersu",
    "ESCAR": "Escar",
    "ESCOM": "Escort",
    "ESEN": "Esenboğa Enerji",
    "ETILR": "Etiler Gıda",
    "ETYAT": "Euro Trend",
    "EUHOL": "Euro Holding",
    "EUKYO": "Euro Kapital",
    "EUPWR": "Europower",
    "EUREN": "Europen",
    "EUYO": "Euro Yatırım",
    "EYGYO": "EYG GYO",
    "FADE": "Fade Gıda",
    "FENER": "Fenerbahçe",
    "FLAP": "Flap Kongre",
    "FMIZP": "Federal Mogul",
    "FONET": "Fonet",
    "FORMT": "Formet",
    "FORTE": "Forte",
    "FRIGO": "Frigo",
    "FRMPL": "Formül Plastik",
    "FROTO": "Ford Otosan",
    "FZLGY": "Fuzul GYO",
    "GARAN": "Garanti",
    "GARFA": "Garanti Faktoring",
    "GATEG": "Gate Group",
    "GEDIK": "Gedik Yatırım",
    "GEDZA": "Gediz Ambalaj",
    "GENIL": "Gen İlaç",
    "GENKM": "Gentaş",
    "GENTS": "Gentaş Dekoratif",
    "GEREL": "Gersan",
    "GESAN": "Girişim Elektrik",
    "GIPTA": "Gıpta Ofis",
    "GLBMD": "Global Menkul",
    "GLCVY": "Gelecek Varlık",
    "GLRMK": "Gülermak",
    "GLRYH": "Güler Yatırım",
    "GLYHO": "Global Yatırım",
    "GMTAS": "Gimat",
    "GOKNR": "Göknur",
    "GOLDA": "Golda",
    "GOLTS": "Göltaş",
    "GOODY": "Goodyear",
    "GOZDE": "Gözde Girişim",
    "GRNYO": "Garanti Yatırım",
    "GRSEL": "Gür-Sel",
    "GRTHO": "GrainTürk",
    "GSDDE": "GSD Denizcilik",
    "GSDHO": "GSD Holding",
    "GSRAY": "Galatasaray",
    "GUBRF": "Gübretaş",
    "GUNDG": "Gündoğdu Gıda",
    "GWIND": "Galata Wind",
    "GZNMI": "Gezinomi",
    "HALKB": "Halkbank",
    "HATEK": "Hateks",
    "HATSN": "Hat-San",
    "HDFGS": "Hedef Girişim",
    "HEDEF": "Hedef Holding",
    "HEKTS": "Hektaş",
    "HKTM": "Hidropar",
    "HLGYO": "Halk GYO",
    "HOROZ": "Horoz Lojistik",
    "HRKET": "Hareket Proje",
    "HTTBT": "Hitit",
    "HUBVC": "Hub Girişim",
    "HUNER": "Hun Enerji",
    "HURGZ": "Hürriyet",
    "ICBCT": "ICBC Turkey",
    "ICUGS": "ICU Girişim",
    "IDGYO": "İdealist GYO",
    "IEYHO": "Işıklar Enerji",
    "IHAAS": "İhlas Haber",
    "IHEVA": "İhlas Ev",
    "IHGZT": "İhlas Gazetecilik",
    "IHLAS": "İhlas Holding",
    "IMASM": "İmaş",
    "INDES": "İndeks Bilgisayar",
    "INFO": "İnfo Yatırım",
    "INGRM": "Ingram Micro",
    "INTEM": "İntema",
    "INVEO": "Inveo",
    "INVES": "Investco",
    "ISATR": "İşBank A",
    "ISBIR": "İşbir",
    "ISBTR": "İşBank B",
    "ISCTR": "İş Bankası",
    "ISDMR": "İsdemir",
    "ISFIN": "İş Finansal",
    "ISGSY": "İş Girişim",
    "ISGYO": "İş GYO",
    "ISKPL": "Işık Plastik",
    "ISKUR": "İşBank Kurucu",
    "ISMEN": "İş Yatırım",
    "ISSEN": "İşbir Sentetik",
    "ISVEA": "İsvea",
    "ISYAT": "İşYatırım Ort.",
    "IZENR": "İzdemir Enerji",
    "IZFAS": "İzmir Fırça",
    "IZINV": "İz Yatırım",
    "IZMDC": "İzmir Demir",
    "JANTS": "Jantsa",
    "KAPLM": "Kaplamin",
    "KAREL": "Karel",
    "KARSN": "Karsan",
    "KARTN": "Kartonsan",
    "KATMR": "Katmerciler",
    "KAYSE": "Kayseri Şeker",
    "KBORU": "Kuzey Boru",
    "KCAER": "Kocaer",
    "KCHOL": "Koç Holding",
    "KENT": "Kent Gıda",
    "KERVN": "Kervansaray",
    "KFEIN": "Kafein Yazılım",
    "KGYO": "Koray GYO",
    "KIMMR": "Kim Market",
    "KLGYO": "Kiler GYO",
    "KLKIM": "Kalekim",
    "KLMSN": "Klimasan",
    "KLNMA": "Kalkınma Bankası",
    "KLRHO": "Kiler Holding",
    "KLSER": "Kaleseramik",
    "KLSYN": "Koleksiyon",
    "KLYPV": "Kalyon PV",
    "KMPUR": "Kimteks",
    "KNFRT": "Konfrut",
    "KOCMT": "Koç Metalurji",
    "KONKA": "Konya Kağıt",
    "KONTR": "Kontrolmatik",
    "KONYA": "Konya Çimento",
    "KOPOL": "Koza Polyester",
    "KORDS": "Kordsa",
    "KOTON": "Koton",
    "KRDMA": "Kardemir A",
    "KRDMB": "Kardemir B",
    "KRDMD": "Kardemir D",
    "KRGYO": "Körfez GYO",
    "KRONT": "Kron Teknoloji",
    "KRPLS": "Koroplast",
    "KRSTL": "Kristal Kola",
    "KRTEK": "Karsu Tekstil",
    "KRVGD": "Kervan Gıda",
    "KSTUR": "Kuştur",
    "KTLEV": "Katılımevim",
    "KTSKR": "Kütahya Şeker",
    "KUTPO": "Kütahya Porselen",
    "KUVVA": "Kuvva Gıda",
    "KUYAS": "Kuyaş",
    "KZBGY": "Kızılbük GYO",
    "KZGYO": "Kuzugrup GYO",
    "LIDER": "LDR Turizm",
    "LIDFA": "Lider Faktoring",
    "LILAK": "Lila Kağıt",
    "LINK": "Link Bilgisayar",
    "LKMNH": "Lokman Hekim",
    "LMKDC": "Limak Doğu",
    "LOGO": "Logo",
    "LRSHO": "Loras Holding",
    "LUKSK": "Lüks Kadife",
    "LXGYO": "Luxera GYO",
    "LYDHO": "Lydia Holding",
    "LYDYE": "Lydia Yeşil",
    "MAALT": "Altınyunus",
    "MACKO": "Mackolik",
    "MAGEN": "Margün Enerji",
    "MAKIM": "Makim",
    "MAKTK": "Makina Takım",
    "MANAS": "Manas Enerji",
    "MARBL": "Tureks Mermer",
    "MARKA": "Marka Yatırım",
    "MARMR": "Marmara Holding",
    "MARTI": "Martı Otel",
    "MAVI": "Mavi",
    "MCARD": "Metropal",
    "MEDTR": "Meditera",
    "MEGAP": "Mega Polietilen",
    "MEGMT": "Mega Metal",
    "MEKAG": "Meka",
    "MEPET": "Mepet",
    "MERCN": "Mercan Kimya",
    "MERIT": "Merit Turizm",
    "MERKO": "Merko Gıda",
    "METRO": "Metro Holding",
    "MEYSU": "Meysu",
    "MGROS": "Migros",
    "MHRGY": "MHR GYO",
    "MIATK": "Mia Teknoloji",
    "MMCAS": "MMC Sanayi",
    "MNDRS": "Menderes Tekstil",
    "MNDTR": "Mondi",
    "MOBTL": "Mobiltel",
    "MOGAN": "Mogan Enerji",
    "MOPAS": "Mopaş",
    "MPARK": "Medical Park",
    "MRGYO": "Martı GYO",
    "MRSHL": "Marshall",
    "MSGYO": "Mistral GYO",
    "MTRKS": "Matriks",
    "MTRYO": "Metro Yatırım",
    "MZHLD": "Mazhar Zorlu",
    "NATEN": "Naturel Enerji",
    "NETAS": "Netaş",
    "NETCD": "Netcad",
    "NIBAS": "Niğbaş",
    "NTGAZ": "Naturelgaz",
    "NTHOL": "Net Holding",
    "NUGYO": "Nurol GYO",
    "NUHCM": "Nuh Çimento",
    "OBAMS": "Oba Makarna",
    "OBASE": "Obase",
    "ODAS": "Odaş",
    "ODINE": "Odine",
    "OFSYM": "Ofis Yem",
    "ONCSM": "Oncosem",
    "ONRYT": "Onur Yüksek",
    "ORGE": "Orge Enerji",
    "ORMA": "Orma",
    "ORZAX": "Orzaks",
    "OSMEN": "Osmanlı Yatırım",
    "OSTIM": "Ostim",
    "OTKAR": "Otokar",
    "OTTO": "Otto Holding",
    "OYAKC": "Oyak Çimento",
    "OYAYO": "Oyak Yatırım",
    "OYLUM": "Oylum",
    "OYYAT": "Oyak Yatırım",
    "OZATD": "Özata Denizcilik",
    "OZGYO": "Özderici GYO",
    "OZKGY": "Özak GYO",
    "OZRDN": "Özerden",
    "OZSUB": "Özsu Balık",
    "OZYSR": "Özyaşar Tel",
    "PAGYO": "Panora GYO",
    "PAHOL": "Pasifik Holding",
    "PAMEL": "Pamel",
    "PAPIL": "Papilon",
    "PARSN": "Parsan",
    "PASEU": "Pasifik Eurasia",
    "PATEK": "Pasifik Teknoloji",
    "PCILT": "PC İletişim",
    "PEKGY": "Peker GYO",
    "PENGD": "Penguen",
    "PENTA": "Penta",
    "PETKM": "Petkim",
    "PETUN": "Pınar Et",
    "PGSUS": "Pegasus",
    "PINSU": "Pınar Su",
    "PKART": "Plastikkart",
    "PKENT": "Petrokent",
    "PLTUR": "Platform Turizm",
    "PNLSN": "Panelsan",
    "PNSUT": "Pınar Süt",
    "POLHO": "Polisan Holding",
    "POLTK": "Politeknik",
    "PRDGS": "Pardus",
    "PRKAB": "Prysmian",
    "PRKME": "Park Elektrik",
    "PRZMA": "Prizma",
    "PSDTC": "Pergamon",
    "PSGYO": "Pasifik GYO",
    "QNBFK": "QNB Finans",
    "QNBTR": "QNB Bank",
    "QUAGR": "Qua Granite",
    "RALYH": "RAL Yatırım",
    "RAYSG": "Ray Sigorta",
    "REEDR": "Reeder",
    "RGYAS": "Rönesans GYO",
    "RNPOL": "Rainbow",
    "RODRG": "Rodrigo",
    "RTALB": "RTA",
    "RUBNS": "Rubenis",
    "RUZYE": "Ruzy Madencilik",
    "RYGYO": "Reysaş GYO",
    "RYSAS": "Reysaş",
    "SAFKR": "Safkar",
    "SAHOL": "Sabancı Holding",
    "SAMAT": "Saray Matbaa",
    "SANEL": "San-El",
    "SANFM": "Sanifoam",
    "SANKO": "Sanko",
    "SARKY": "Sarkuysan",
    "SASA": "Sasa",
    "SAYAS": "Say Yenilenebilir",
    "SDTTR": "SDT Uzay",
    "SEGMN": "Seğmen",
    "SEGYO": "Şeker GYO",
    "SEKFK": "Şeker Faktoring",
    "SEKUR": "Sekuro",
    "SELEC": "Selçuk Ecza",
    "SELVA": "Selva",
    "SERNT": "Seranit",
    "SEYKM": "Seyitler",
    "SILVR": "Silverline",
    "SISE": "Şişecam",
    "SKBNK": "Şekerbank",
    "SKTAS": "Söktaş",
    "SKYLP": "Skyalp",
    "SKYMD": "Şeker Yatırım",
    "SMART": "Smartiks",
    "SMRTG": "Smart Güneş",
    "SMRVA": "Sümer Varlık",
    "SNGYO": "Sinpaş GYO",
    "SNICA": "Sanica",
    "SNPAM": "Sönmez Pamuk",
    "SODSN": "Sodaş",
    "SOHOE": "Soho Giyim",
    "SOKE": "Söke",
    "SOKM": "Şok",
    "SONME": "Sönmez Filament",
    "SRVGY": "Servet GYO",
    "SSAAT": "Saat&Saat",
    "SUMAS": "Sumaş",
    "SUNTK": "Sun Tekstil",
    "SURGY": "Sur Yapı",
    "SUWEN": "Suwen",
    "SVGYO": "Savur GYO",
    "TABGD": "TAB Gıda",
    "TARKM": "Tarkim",
    "TATEN": "Tatlıpınar",
    "TATGD": "Tat",
    "TAVHL": "TAV",
    "TBORG": "Tuborg",
    "TCELL": "Turkcell",
    "TCKRC": "Kıraç Galvaniz",
    "TDGYO": "Trend GYO",
    "TEHOL": "Tera Holding",
    "TEKTU": "Tek-Art",
    "TERA": "Tera Yatırım",
    "TEZOL": "Tezol",
    "TGSAS": "TGS",
    "THYAO": "THY",
    "TKFEN": "Tekfen",
    "TKNSA": "Teknosa",
    "TLMAN": "Trabzon Liman",
    "TMPOL": "Temapol",
    "TMSN": "Tümosan",
    "TNZTP": "Tapdi Oksijen",
    "TOASO": "Tofaş",
    "TRALT": "Türk Altın",
    "TRCAS": "Turcas",
    "TRENJ": "Türkiye Enerji",
    "TRGYO": "Torunlar GYO",
    "TRHOL": "Tera Finansal",
    "TRILC": "Turk İlaç",
    "TRMET": "TR Metal",
    "TSGYO": "TSKB GYO",
    "TSKB": "TSKB",
    "TSPOR": "Trabzonspor",
    "TTKOM": "Türk Telekom",
    "TTRAK": "Türk Traktör",
    "TUCLK": "Tuğçelik",
    "TUKAS": "Tukaş",
    "TUPRS": "Tüpraş",
    "TUREX": "Tureks Turizm",
    "TURGG": "Türker Proje",
    "TURSG": "Türkiye Sigorta",
    "UCAYM": "Üçay Mühendislik",
    "UFUK": "Ufuk Yönetim",
    "ULAS": "Ulaşlar Turizm",
    "ULKER": "Ülker",
    "ULUFA": "Ulusal Faktoring",
    "ULUSE": "Ulusoy Elektrik",
    "ULUUN": "Ulusoy Un",
    "UNLU": "Ünlü Yatırım",
    "USAK": "Uşak Seramik",
    "VAKBN": "VakıfBank",
    "VAKFA": "Vakıf Faktoring",
    "VAKFN": "Vakıf Finansal",
    "VAKKO": "Vakko",
    "VANGD": "Vanet",
    "VBTYZ": "VBT Yazılım",
    "VERUS": "Verusa",
    "VESBE": "Vestel Beyaz",
    "VESTL": "Vestel",
    "VKFYO": "Vakıf Yatırım",
    "VKGYO": "Vakıf GYO",
    "VKING": "Viking",
    "VRGYO": "Vera GYO",
    "VSNMD": "Vişne Madencilik",
    "YAPRK": "Yaprak Süt",
    "YATAS": "Yataş",
    "YAYLA": "Yayla Enerji",
    "YBTAS": "Yibitaş",
    "YEOTK": "YEO",
    "YESIL": "Yeşil Holding",
    "YGGYO": "Yeni Gimat",
    "YIGIT": "Yiğit Akü",
    "YKBNK": "Yapı Kredi",
    "YKSLN": "Yükselen Çelik",
    "YONGA": "Yonga",
    "YUNSA": "Yünsa",
    "YYAPI": "Yeşil Yapı",
    "YYLGD": "Yayla Agro",
    "ZEDUR": "Zedur",
    "ZERGY": "Zeray GYO",
    "ZGYO": "Z GYO",
    "ZOREN": "Zorlu Enerji",
    "ZRGYO": "Ziraat GYO",
}


def get_ai_narrative_name(ticker: str) -> str | None:
    """BIST sembolünün AI anlatımındaki kısa adını döndürür."""
    clean_ticker = str(ticker or "").replace(".IS", "").replace("-USD", "").replace("=F", "")
    return AI_NARRATIVE_SHORT_NAMES.get(clean_ticker)
